# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 00:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallDayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_api_calls', models.PositiveIntegerField(verbose_name=b'API call amount')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name=b'Creation date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'unshorten_profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APICallMonthHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_api_calls', models.PositiveIntegerField(verbose_name=b'API call amount')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name=b'Creation date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'unshorten_profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnshortenURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Creation date')),
                ('long_url', models.CharField(max_length=4000, verbose_name=b'Long URL')),
                ('short_url', models.CharField(max_length=1024, verbose_name=b'Short URL')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='apicallmonthhistory',
            unique_together=set([('creation_date', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='apicalldayhistory',
            unique_together=set([('creation_date', 'user')]),
        ),
    ]
